# Build Stage
FROM golang:1.20 AS builder

# Set working directory
WORKDIR /app

# Copy Go module files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the Go binary
RUN go build -o cctweakedaudioconverter .

# Runtime Stage
FROM linuxserver/ffmpeg:version-7.1-cli

# Set working directory
WORKDIR /app

# Copy the compiled Go binary from the builder stage
COPY --from=builder /app/cctweakedaudioconverter .

# Expose the server port
EXPOSE 8080

# Set the entry point
ENTRYPOINT [ "./cctweakedaudioconverter" ]
